/*
 * Created on 10 Feb 2016 ( Time 11:17:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.bean;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'UserTransaction' entity
 * 
 * @author Telosys Tools
 *
 */
public class UserTransaction implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : transaction_id INT 
    private Integer transactionId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : user_id VARCHAR 
    private String userId;

    // DB : transaction_name VARCHAR 
    private String transactionName;

    // DB : transaction_type VARCHAR 
    private String transactionType;

    // DB : transaction_status VARCHAR 
    private String transactionStatus;

    // DB : transaction_time TIMESTAMP 
    private Date transactionTime;

    // DB : created_date DATE 
    private Date createdDate;

    // DB : updated_date DATE 
    private Date updatedDate;

    // DB : created_by VARCHAR 
    private String createdBy;

    // DB : updated_by VARCHAR 
    private String updatedBy;

    // DB : status VARCHAR 
    private String status;

    // DB : is_active VARCHAR 
    private String isActive;

    // DB : version INT 
    private Integer version;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setTransactionId( Integer transactionId ) {
        this.transactionId = transactionId ;
    }

    public Integer getTransactionId() {
        return this.transactionId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserId( String userId ) {
        this.userId = userId;
    }
    public String getUserId() {
        return this.userId;
    }

    public void setTransactionName( String transactionName ) {
        this.transactionName = transactionName;
    }
    public String getTransactionName() {
        return this.transactionName;
    }

    public void setTransactionType( String transactionType ) {
        this.transactionType = transactionType;
    }
    public String getTransactionType() {
        return this.transactionType;
    }

    public void setTransactionStatus( String transactionStatus ) {
        this.transactionStatus = transactionStatus;
    }
    public String getTransactionStatus() {
        return this.transactionStatus;
    }

    public void setTransactionTime( Date transactionTime ) {
        this.transactionTime = transactionTime;
    }
    public Date getTransactionTime() {
        return this.transactionTime;
    }

    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setUpdatedDate( Date updatedDate ) {
        this.updatedDate = updatedDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setUpdatedBy( String updatedBy ) {
        this.updatedBy = updatedBy;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }

    public void setIsActive( String isActive ) {
        this.isActive = isActive;
    }
    public String getIsActive() {
        return this.isActive;
    }

    public void setVersion( Integer version ) {
        this.version = version;
    }
    public Integer getVersion() {
        return this.version;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(transactionId);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(transactionName);
        sb.append("|");
        sb.append(transactionType);
        sb.append("|");
        sb.append(transactionStatus);
        sb.append("|");
        sb.append(transactionTime);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(updatedDate);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(updatedBy);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(isActive);
        sb.append("|");
        sb.append(version);
        return sb.toString(); 
    } 


}
