/*
 * Created on 5 Mar 2016 ( Time 18:48:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao.impl.spring;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;

import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import com.mealtime.bean.AmUpdatedItems;
import com.mealtime.dao.AmUpdatedItemsDAO;
import com.mealtime.dao.impl.spring.commons.GenericDAO;

/**
 * AmUpdatedItems DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
@Repository
public class AmUpdatedItemsDAOImplSpring extends GenericDAO<AmUpdatedItems> implements AmUpdatedItemsDAO {

	private final static String SQL_SELECT = 
			"select id, item_id, user_id, modified_item_date, created_date, updated_date, created_by, updated_by, status, is_active, version from am_updated_items where id = ?";

	private final static String SQL_SELECTBY_USERID = 
			"select id, item_id, user_id, modified_item_date, created_date, updated_date, created_by, updated_by, status, is_active, version from am_updated_items where user_id = ?";
	
	// NB : This entity has an auto-incremented primary key : "id"
	private final static String AUTO_INCREMENTED_COLUMN = "id";

	private final static int[] SQL_INSERT_TYPES = new int[] {
			java.sql.Types.INTEGER ,  // "item_id" : INT - java.lang.Integer
			java.sql.Types.VARCHAR ,  // "user_id" : INT - java.lang.Integer
			java.sql.Types.DATE ,  // "modified_item_date" : DATE - java.util.Date
			java.sql.Types.DATE ,  // "created_date" : DATE - java.util.Date
			java.sql.Types.DATE ,  // "updated_date" : DATE - java.util.Date
			java.sql.Types.VARCHAR ,  // "created_by" : VARCHAR(255) - java.lang.String
			java.sql.Types.VARCHAR ,  // "updated_by" : VARCHAR(255) - java.lang.String
			java.sql.Types.VARCHAR ,  // "status" : VARCHAR(255) - java.lang.String
			java.sql.Types.VARCHAR ,  // "is_active" : VARCHAR(255) - java.lang.String
			java.sql.Types.INTEGER   // "version" : INT - java.lang.Integer
	};

	private final static String SQL_INSERT = 
		"insert into am_updated_items ( item_id, user_id, modified_item_date, created_date, updated_date, created_by, updated_by, status, is_active, version ) values ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update am_updated_items set item_id = ?, user_id = ?, modified_item_date = ?, created_date = ?, updated_date = ?, created_by = ?, updated_by = ?, status = ?, is_active = ?, version = ? where id = ?";

	private final static String UPDATE_USERRECORD = 
	"update am_updated_items set modified_item_date = ?, status = ? where user_id = ?";

	private final static String SQL_DELETE = 
		"delete from am_updated_items where id = ?";
	
	private final static String DELETE_USERRECORD = 
			"delete from am_updated_items where item_id = ? and user_id = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from am_updated_items";

	private final static String SQL_COUNT = 
		"select count(*) from am_updated_items where id = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public AmUpdatedItemsDAOImplSpring() {
		super(AUTO_INCREMENTED_COLUMN, SQL_INSERT_TYPES);
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public AmUpdatedItems find( Integer id ) {
		Object[] primaryKey = new Object[] { id };
		return super.doSelect(primaryKey);		
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public boolean load( AmUpdatedItems amUpdatedItems ) {
		return super.doSelect(amUpdatedItems) ;
	}
	
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public Integer insert(AmUpdatedItems amUpdatedItems) {
		Long key = super.doInsertAutoIncr(amUpdatedItems);
		return key.intValue();
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public int update(AmUpdatedItems amUpdatedItems) {
		return super.doUpdate(amUpdatedItems);
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public int delete( Integer id ) {
		Object[] primaryKey = new Object[] { id };
		return super.doDelete(primaryKey);		
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public int delete( AmUpdatedItems amUpdatedItems ) {
		return super.doDelete(amUpdatedItems);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public boolean exists( Integer id ) {
		Object[] primaryKey = new Object[] { id };
		return super.doExists(primaryKey);
	}
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public boolean exists( AmUpdatedItems amUpdatedItems ) {
		return super.doExists(amUpdatedItems);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	// Super class abstract methods implementation
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}
	//----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForInsert(AmUpdatedItems amUpdatedItems)  {
		return new Object[] {
			//--- Returns PRIMARY KEY and DATA ( for SQL "SET x=?, y=?, ..." )
			// "id" is auto-incremented => no set in insert		
			amUpdatedItems.getItemId() , // "item_id" : java.lang.Integer
			amUpdatedItems.getUserId() , // "user_id" : java.lang.Integer
			amUpdatedItems.getModifiedItemDate() , // "modified_item_date" : java.util.Date
			amUpdatedItems.getCreatedDate() , // "created_date" : java.util.Date
			amUpdatedItems.getUpdatedDate() , // "updated_date" : java.util.Date
			amUpdatedItems.getCreatedBy() , // "created_by" : java.lang.String
			amUpdatedItems.getUpdatedBy() , // "updated_by" : java.lang.String
			amUpdatedItems.getStatus() , // "status" : java.lang.String
			amUpdatedItems.getIsActive() , // "is_active" : java.lang.String
			amUpdatedItems.getVersion()  // "version" : java.lang.Integer
		};
	}
    //----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForUpdate(AmUpdatedItems amUpdatedItems) {
		return new Object[] {		
			//--- Returns DATA first ( for SQL "SET x=?, y=?, ..." )
			amUpdatedItems.getItemId(), // "item_id" : java.lang.Integer
			amUpdatedItems.getUserId(), // "user_id" : java.lang.Integer
			amUpdatedItems.getModifiedItemDate(), // "modified_item_date" : java.util.Date
			amUpdatedItems.getCreatedDate(), // "created_date" : java.util.Date
			amUpdatedItems.getUpdatedDate(), // "updated_date" : java.util.Date
			amUpdatedItems.getCreatedBy(), // "created_by" : java.lang.String
			amUpdatedItems.getUpdatedBy(), // "updated_by" : java.lang.String
			amUpdatedItems.getStatus(), // "status" : java.lang.String
			amUpdatedItems.getIsActive(), // "is_active" : java.lang.String
			amUpdatedItems.getVersion(), // "version" : java.lang.Integer
			//--- Returns PRIMARY KEY at the end ( for SQL "WHERE key=?, ..." )
			amUpdatedItems.getId()  // "id" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForPrimaryKey(AmUpdatedItems amUpdatedItems)  {
		return new Object[] {
			//--- Returns PRIMARY KEY values ( for SQL "WHERE key=?, ..." )
			amUpdatedItems.getId()  // "id" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	@Override
	protected RowMapper<AmUpdatedItems> getRowMapper(AmUpdatedItems o)  {
		//--- RowMapper to populate the given bean instance
		return new AmUpdatedItemsRowMapper(o) ;
	}
	//----------------------------------------------------------------------
	@Override
	protected RowMapper<AmUpdatedItems> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		return new AmUpdatedItemsRowMapper( new AmUpdatedItems() ) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param amUpdatedItems
	 * @throws SQLException
	 */
	private void populateBean(ResultSet rs, AmUpdatedItems amUpdatedItems) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		amUpdatedItems.setId(rs.getInt("id")); // java.lang.Integer
		if ( rs.wasNull() ) { amUpdatedItems.setId(null); }; // not primitive number => keep null value if any
		amUpdatedItems.setItemId(rs.getInt("item_id")); // java.lang.Integer
		if ( rs.wasNull() ) { amUpdatedItems.setItemId(null); }; // not primitive number => keep null value if any
		amUpdatedItems.setUserId(rs.getString("user_id")); // java.lang.Integer
		if ( rs.wasNull() ) { amUpdatedItems.setUserId(null); }; // not primitive number => keep null value if any
		amUpdatedItems.setModifiedItemDate(rs.getDate("modified_item_date")); // java.util.Date
		amUpdatedItems.setCreatedDate(rs.getDate("created_date")); // java.util.Date
		amUpdatedItems.setUpdatedDate(rs.getDate("updated_date")); // java.util.Date
		amUpdatedItems.setCreatedBy(rs.getString("created_by")); // java.lang.String
		amUpdatedItems.setUpdatedBy(rs.getString("updated_by")); // java.lang.String
		amUpdatedItems.setStatus(rs.getString("status")); // java.lang.String
		amUpdatedItems.setIsActive(rs.getString("is_active")); // java.lang.String
		amUpdatedItems.setVersion(rs.getInt("version")); // java.lang.Integer
		if ( rs.wasNull() ) { amUpdatedItems.setVersion(null); }; // not primitive number => keep null value if any
	}

    //----------------------------------------------------------------------
	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	private class AmUpdatedItemsRowMapper implements RowMapper<AmUpdatedItems> {

		/**
		 * The bean instance that will be populated from the ResultSet
		 */
		private final AmUpdatedItems bean ;
		
		/**
		 * Constructor
		 * @param bean the bean to be populated 
		 */
		AmUpdatedItemsRowMapper(AmUpdatedItems bean) {
			this.bean = bean ;
		}
		
		public AmUpdatedItems mapRow(ResultSet rs, int rowNum) throws SQLException {
			populateBean(rs, this.bean);
			return this.bean;
		}
	}

	public AmUpdatedItems findByUserId(String userId) {
		try{
			return getJdbcTemplate().queryForObject(SQL_SELECTBY_USERID, new Object[]{userId},getRowMapper());
		}catch(EmptyResultDataAccessException e){
			System.out.println("Exception in findByUserId:::"+e.getMessage());
		}
		return null;
	}

	public int deleteUserRecord(int itemId, String userId) {
		try{
			int i = getJdbcTemplate().update(DELETE_USERRECORD, new Object[]{itemId,userId});
			return i;
		}catch(EmptyResultDataAccessException e){
			System.out.println("Exception in deleteUserRecord:::"+e.getMessage());
		}
		return 1;
	}
	
	public int updateUserRecord(String userId,Date date,String Status) {
		try{
			int i = getJdbcTemplate().update(UPDATE_USERRECORD, new Object[]{date,Status,userId});
			return i;
		}catch(EmptyResultDataAccessException e){
			System.out.println("Exception in updateUserRecord:::"+e.getMessage());
		}
		return 1;
	}
}
