/*
 * Created on 15 Jan 2016 ( Time 19:53:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao.impl.spring;

import java.sql.ResultSet;
import java.sql.SQLException;

import com.mealtime.bean.MealsMaster;
import com.mealtime.dao.MealsMasterDAO;
import com.mealtime.dao.impl.spring.commons.GenericDAO;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

/**
 * MealsMaster DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
@Repository
public class MealsMasterDAOImplSpring extends GenericDAO<MealsMaster> implements MealsMasterDAO {

	private final static String SQL_SELECT = 
		"select meal_id, meal_name, meal_type, created_date, updated_date, created_by, updated_by, status, is_active, version from meals_master where meal_id = ?";


	private final static String SQL_INSERT = 
		"insert into meals_master ( meal_id, meal_name, meal_type, created_date, updated_date, created_by, updated_by, status, is_active, version ) values ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update meals_master set meal_name = ?, meal_type = ?, created_date = ?, updated_date = ?, created_by = ?, updated_by = ?, status = ?, is_active = ?, version = ? where meal_id = ?";

	private final static String SQL_DELETE = 
		"delete from meals_master where meal_id = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from meals_master";

	private final static String SQL_COUNT = 
		"select count(*) from meals_master where meal_id = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public MealsMasterDAOImplSpring() {
		super();
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public MealsMaster find( Integer mealId ) {
		Object[] primaryKey = new Object[] { mealId };
		return super.doSelect(primaryKey);		
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public boolean load( MealsMaster mealsMaster ) {
		return super.doSelect(mealsMaster) ;
	}
	
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public void insert(MealsMaster mealsMaster) {
		super.doInsert(mealsMaster);
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public int update(MealsMaster mealsMaster) {
		return super.doUpdate(mealsMaster);
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public int delete( Integer mealId ) {
		Object[] primaryKey = new Object[] { mealId };
		return super.doDelete(primaryKey);		
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public int delete( MealsMaster mealsMaster ) {
		return super.doDelete(mealsMaster);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public boolean exists( Integer mealId ) {
		Object[] primaryKey = new Object[] { mealId };
		return super.doExists(primaryKey);
	}
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public boolean exists( MealsMaster mealsMaster ) {
		return super.doExists(mealsMaster);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	// Super class abstract methods implementation
    //----------------------------------------------------------------------
	
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}
	//----------------------------------------------------------------------
	
	protected Object[] getValuesForInsert(MealsMaster mealsMaster)  {
		return new Object[] {
			//--- Returns PRIMARY KEY and DATA ( for SQL "SET x=?, y=?, ..." )
			mealsMaster.getMealId() , // "meal_id" : java.lang.Integer
			mealsMaster.getMealName() , // "meal_name" : java.lang.String
			mealsMaster.getMealType() , // "meal_type" : java.lang.String
			mealsMaster.getCreatedDate() , // "created_date" : java.util.Date
			mealsMaster.getUpdatedDate() , // "updated_date" : java.util.Date
			mealsMaster.getCreatedBy() , // "created_by" : java.lang.String
			mealsMaster.getUpdatedBy() , // "updated_by" : java.lang.String
			mealsMaster.getStatus() , // "status" : java.lang.String
			mealsMaster.getIsActive() , // "is_active" : java.lang.String
			mealsMaster.getVersion()  // "version" : java.lang.Integer
		};
	}
    //----------------------------------------------------------------------
	
	protected Object[] getValuesForUpdate(MealsMaster mealsMaster) {
		return new Object[] {		
			//--- Returns DATA first ( for SQL "SET x=?, y=?, ..." )
			mealsMaster.getMealName(), // "meal_name" : java.lang.String
			mealsMaster.getMealType(), // "meal_type" : java.lang.String
			mealsMaster.getCreatedDate(), // "created_date" : java.util.Date
			mealsMaster.getUpdatedDate(), // "updated_date" : java.util.Date
			mealsMaster.getCreatedBy(), // "created_by" : java.lang.String
			mealsMaster.getUpdatedBy(), // "updated_by" : java.lang.String
			mealsMaster.getStatus(), // "status" : java.lang.String
			mealsMaster.getIsActive(), // "is_active" : java.lang.String
			mealsMaster.getVersion(), // "version" : java.lang.Integer
			//--- Returns PRIMARY KEY at the end ( for SQL "WHERE key=?, ..." )
			mealsMaster.getMealId()  // "meal_id" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	
	protected Object[] getValuesForPrimaryKey(MealsMaster mealsMaster)  {
		return new Object[] {
			//--- Returns PRIMARY KEY values ( for SQL "WHERE key=?, ..." )
			mealsMaster.getMealId()  // "meal_id" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	
	protected RowMapper<MealsMaster> getRowMapper(MealsMaster o)  {
		//--- RowMapper to populate the given bean instance
		return new MealsMasterRowMapper(o) ;
	}
	//----------------------------------------------------------------------
	
	protected RowMapper<MealsMaster> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		return new MealsMasterRowMapper( new MealsMaster() ) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param mealsMaster
	 * @throws SQLException
	 */
	private void populateBean(ResultSet rs, MealsMaster mealsMaster) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		mealsMaster.setMealId(rs.getInt("meal_id")); // java.lang.Integer
		if ( rs.wasNull() ) { mealsMaster.setMealId(null); }; // not primitive number => keep null value if any
		mealsMaster.setMealName(rs.getString("meal_name")); // java.lang.String
		mealsMaster.setMealType(rs.getString("meal_type")); // java.lang.String
		mealsMaster.setCreatedDate(rs.getDate("created_date")); // java.util.Date
		mealsMaster.setUpdatedDate(rs.getDate("updated_date")); // java.util.Date
		mealsMaster.setCreatedBy(rs.getString("created_by")); // java.lang.String
		mealsMaster.setUpdatedBy(rs.getString("updated_by")); // java.lang.String
		mealsMaster.setStatus(rs.getString("status")); // java.lang.String
		mealsMaster.setIsActive(rs.getString("is_active")); // java.lang.String
		mealsMaster.setVersion(rs.getInt("version")); // java.lang.Integer
		if ( rs.wasNull() ) { mealsMaster.setVersion(null); }; // not primitive number => keep null value if any
	}

    //----------------------------------------------------------------------
	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	private class MealsMasterRowMapper implements RowMapper<MealsMaster> {

		/**
		 * The bean instance that will be populated from the ResultSet
		 */
		private final MealsMaster bean ;
		
		/**
		 * Constructor
		 * @param bean the bean to be populated 
		 */
		MealsMasterRowMapper(MealsMaster bean) {
			this.bean = bean ;
		}
		
		
		public MealsMaster mapRow(ResultSet rs, int rowNum) throws SQLException {
			populateBean(rs, this.bean);
			return this.bean;
		}
	}
}
