/*
 * Created on 5 Mar 2016 ( Time 18:48:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao.impl.spring;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import com.mealtime.bean.PmItems;
import com.mealtime.dao.PmItemsDAO;
import com.mealtime.dao.impl.spring.commons.GenericDAO;

/**
 * PmItems DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
@Repository
public class PmItemsDAOImplSpring extends GenericDAO<PmItems> implements PmItemsDAO {

	private final static String SQL_SELECT = 
		"select item_id, item_name, item_desc, item_image, item_price, item_date, created_date, updated_date, created_by, updated_by, status, is_active, version from pm_items where item_id = ?";

	// NB : This entity has an auto-incremented primary key : "item_id"
	private final static String AUTO_INCREMENTED_COLUMN = "item_id";

	private final static int[] SQL_INSERT_TYPES = new int[] {
			java.sql.Types.VARCHAR ,  // "item_name" : VARCHAR(255) - java.lang.String
			java.sql.Types.VARCHAR ,  // "item_desc" : VARCHAR(255) - java.lang.String
			java.sql.Types.VARCHAR ,  // "item_image" : VARCHAR(255) - java.lang.String
			java.sql.Types.DOUBLE ,  // "item_price" : DOUBLE - java.lang.Double
			java.sql.Types.DATE ,  // "item_date" : DATE - java.util.Date
			java.sql.Types.DATE ,  // "created_date" : DATE - java.util.Date
			java.sql.Types.DATE ,  // "updated_date" : DATE - java.util.Date
			java.sql.Types.VARCHAR ,  // "created_by" : VARCHAR(255) - java.lang.String
			java.sql.Types.VARCHAR ,  // "updated_by" : VARCHAR(255) - java.lang.String
			java.sql.Types.VARCHAR ,  // "status" : VARCHAR(255) - java.lang.String
			java.sql.Types.VARCHAR ,  // "is_active" : VARCHAR(255) - java.lang.String
			java.sql.Types.INTEGER   // "version" : INT - java.lang.Integer
	};

	private final static String SQL_INSERT = 
		"insert into pm_items ( item_name, item_desc, item_image, item_price, item_date, created_date, updated_date, created_by, updated_by, status, is_active, version ) values ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update pm_items set item_name = ?, item_desc = ?, item_image = ?, item_price = ?, item_date = ?, created_date = ?, updated_date = ?, created_by = ?, updated_by = ?, status = ?, is_active = ?, version = ? where item_id = ?";

	private final static String SQL_DELETE = 
		"delete from pm_items where item_id = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from pm_items";

	private final static String SQL_COUNT = 
		"select count(*) from pm_items where item_id = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public PmItemsDAOImplSpring() {
		super(AUTO_INCREMENTED_COLUMN, SQL_INSERT_TYPES);
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public PmItems find( Integer itemId ) {
		Object[] primaryKey = new Object[] { itemId };
		return super.doSelect(primaryKey);		
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public boolean load( PmItems pmItems ) {
		return super.doSelect(pmItems) ;
	}
	
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public Integer insert(PmItems pmItems) {
		Long key = super.doInsertAutoIncr(pmItems);
		return key.intValue();
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public int update(PmItems pmItems) {
		return super.doUpdate(pmItems);
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public int delete( Integer itemId ) {
		Object[] primaryKey = new Object[] { itemId };
		return super.doDelete(primaryKey);		
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public int delete( PmItems pmItems ) {
		return super.doDelete(pmItems);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public boolean exists( Integer itemId ) {
		Object[] primaryKey = new Object[] { itemId };
		return super.doExists(primaryKey);
	}
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public boolean exists( PmItems pmItems ) {
		return super.doExists(pmItems);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	// Super class abstract methods implementation
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}
	//----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForInsert(PmItems pmItems)  {
		return new Object[] {
			//--- Returns PRIMARY KEY and DATA ( for SQL "SET x=?, y=?, ..." )
			// "item_id" is auto-incremented => no set in insert		
			pmItems.getItemName() , // "item_name" : java.lang.String
			pmItems.getItemDesc() , // "item_desc" : java.lang.String
			pmItems.getItemImage() , // "item_image" : java.lang.String
			pmItems.getItemPrice() , // "item_price" : java.lang.Double
			pmItems.getItemDate() , // "item_date" : java.util.Date
			pmItems.getCreatedDate() , // "created_date" : java.util.Date
			pmItems.getUpdatedDate() , // "updated_date" : java.util.Date
			pmItems.getCreatedBy() , // "created_by" : java.lang.String
			pmItems.getUpdatedBy() , // "updated_by" : java.lang.String
			pmItems.getStatus() , // "status" : java.lang.String
			pmItems.getIsActive() , // "is_active" : java.lang.String
			pmItems.getVersion()  // "version" : java.lang.Integer
		};
	}
    //----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForUpdate(PmItems pmItems) {
		return new Object[] {		
			//--- Returns DATA first ( for SQL "SET x=?, y=?, ..." )
			pmItems.getItemName(), // "item_name" : java.lang.String
			pmItems.getItemDesc(), // "item_desc" : java.lang.String
			pmItems.getItemImage(), // "item_image" : java.lang.String
			pmItems.getItemPrice(), // "item_price" : java.lang.Double
			pmItems.getItemDate(), // "item_date" : java.util.Date
			pmItems.getCreatedDate(), // "created_date" : java.util.Date
			pmItems.getUpdatedDate(), // "updated_date" : java.util.Date
			pmItems.getCreatedBy(), // "created_by" : java.lang.String
			pmItems.getUpdatedBy(), // "updated_by" : java.lang.String
			pmItems.getStatus(), // "status" : java.lang.String
			pmItems.getIsActive(), // "is_active" : java.lang.String
			pmItems.getVersion(), // "version" : java.lang.Integer
			//--- Returns PRIMARY KEY at the end ( for SQL "WHERE key=?, ..." )
			pmItems.getItemId()  // "item_id" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForPrimaryKey(PmItems pmItems)  {
		return new Object[] {
			//--- Returns PRIMARY KEY values ( for SQL "WHERE key=?, ..." )
			pmItems.getItemId()  // "item_id" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	@Override
	protected RowMapper<PmItems> getRowMapper(PmItems o)  {
		//--- RowMapper to populate the given bean instance
		return new PmItemsRowMapper(o) ;
	}
	//----------------------------------------------------------------------
	@Override
	protected RowMapper<PmItems> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		return new PmItemsRowMapper( new PmItems() ) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param pmItems
	 * @throws SQLException
	 */
	private void populateBean(ResultSet rs, PmItems pmItems) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		pmItems.setItemId(rs.getInt("item_id")); // java.lang.Integer
		if ( rs.wasNull() ) { pmItems.setItemId(null); }; // not primitive number => keep null value if any
		pmItems.setItemName(rs.getString("item_name")); // java.lang.String
		pmItems.setItemDesc(rs.getString("item_desc")); // java.lang.String
		pmItems.setItemImage(rs.getString("item_image")); // java.lang.String
		pmItems.setItemPrice(rs.getDouble("item_price")); // java.lang.Double
		if ( rs.wasNull() ) { pmItems.setItemPrice(null); }; // not primitive number => keep null value if any
		pmItems.setItemDate(rs.getDate("item_date")); // java.util.Date
		pmItems.setCreatedDate(rs.getDate("created_date")); // java.util.Date
		pmItems.setUpdatedDate(rs.getDate("updated_date")); // java.util.Date
		pmItems.setCreatedBy(rs.getString("created_by")); // java.lang.String
		pmItems.setUpdatedBy(rs.getString("updated_by")); // java.lang.String
		pmItems.setStatus(rs.getString("status")); // java.lang.String
		pmItems.setIsActive(rs.getString("is_active")); // java.lang.String
		pmItems.setVersion(rs.getInt("version")); // java.lang.Integer
		if ( rs.wasNull() ) { pmItems.setVersion(null); }; // not primitive number => keep null value if any
	}

    //----------------------------------------------------------------------
	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	private class PmItemsRowMapper implements RowMapper<PmItems> {

		/**
		 * The bean instance that will be populated from the ResultSet
		 */
		private final PmItems bean ;
		
		/**
		 * Constructor
		 * @param bean the bean to be populated 
		 */
		PmItemsRowMapper(PmItems bean) {
			this.bean = bean ;
		}
		
		public PmItems mapRow(ResultSet rs, int rowNum) throws SQLException {
			populateBean(rs, this.bean);
			return this.bean;
		}
	}
}
