/*
 * Created on 5 Mar 2016 ( Time 18:48:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao.impl.spring;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import com.mealtime.bean.PmUpdatedItems;
import com.mealtime.dao.PmUpdatedItemsDAO;
import com.mealtime.dao.impl.spring.commons.GenericDAO;

/**
 * PmUpdatedItems DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
@Repository
public class PmUpdatedItemsDAOImplSpring extends GenericDAO<PmUpdatedItems> implements PmUpdatedItemsDAO {

	private final static String SQL_SELECT = 
		"select id, item_id, user_id, modified_item_date, created_date, updated_date, created_by, updated_by, status, is_active, version from pm_updated_items where id = ?";

	// NB : This entity has an auto-incremented primary key : "id"
	private final static String AUTO_INCREMENTED_COLUMN = "id";

	private final static int[] SQL_INSERT_TYPES = new int[] {
			java.sql.Types.INTEGER ,  // "item_id" : INT - java.lang.Integer
			java.sql.Types.INTEGER ,  // "user_id" : INT - java.lang.Integer
			java.sql.Types.DATE ,  // "modified_item_date" : DATE - java.util.Date
			java.sql.Types.DATE ,  // "created_date" : DATE - java.util.Date
			java.sql.Types.DATE ,  // "updated_date" : DATE - java.util.Date
			java.sql.Types.VARCHAR ,  // "created_by" : VARCHAR(255) - java.lang.String
			java.sql.Types.VARCHAR ,  // "updated_by" : VARCHAR(255) - java.lang.String
			java.sql.Types.VARCHAR ,  // "status" : VARCHAR(255) - java.lang.String
			java.sql.Types.VARCHAR ,  // "is_active" : VARCHAR(255) - java.lang.String
			java.sql.Types.INTEGER   // "version" : INT - java.lang.Integer
	};

	private final static String SQL_INSERT = 
		"insert into pm_updated_items ( item_id, user_id, modified_item_date, created_date, updated_date, created_by, updated_by, status, is_active, version ) values ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update pm_updated_items set item_id = ?, user_id = ?, modified_item_date = ?, created_date = ?, updated_date = ?, created_by = ?, updated_by = ?, status = ?, is_active = ?, version = ? where id = ?";

	private final static String SQL_DELETE = 
		"delete from pm_updated_items where id = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from pm_updated_items";

	private final static String SQL_COUNT = 
		"select count(*) from pm_updated_items where id = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public PmUpdatedItemsDAOImplSpring() {
		super(AUTO_INCREMENTED_COLUMN, SQL_INSERT_TYPES);
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public PmUpdatedItems find( Integer id ) {
		Object[] primaryKey = new Object[] { id };
		return super.doSelect(primaryKey);		
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public boolean load( PmUpdatedItems pmUpdatedItems ) {
		return super.doSelect(pmUpdatedItems) ;
	}
	
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public Integer insert(PmUpdatedItems pmUpdatedItems) {
		Long key = super.doInsertAutoIncr(pmUpdatedItems);
		return key.intValue();
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public int update(PmUpdatedItems pmUpdatedItems) {
		return super.doUpdate(pmUpdatedItems);
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public int delete( Integer id ) {
		Object[] primaryKey = new Object[] { id };
		return super.doDelete(primaryKey);		
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public int delete( PmUpdatedItems pmUpdatedItems ) {
		return super.doDelete(pmUpdatedItems);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public boolean exists( Integer id ) {
		Object[] primaryKey = new Object[] { id };
		return super.doExists(primaryKey);
	}
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public boolean exists( PmUpdatedItems pmUpdatedItems ) {
		return super.doExists(pmUpdatedItems);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	// Super class abstract methods implementation
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}
	//----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForInsert(PmUpdatedItems pmUpdatedItems)  {
		return new Object[] {
			//--- Returns PRIMARY KEY and DATA ( for SQL "SET x=?, y=?, ..." )
			// "id" is auto-incremented => no set in insert		
			pmUpdatedItems.getItemId() , // "item_id" : java.lang.Integer
			pmUpdatedItems.getUserId() , // "user_id" : java.lang.Integer
			pmUpdatedItems.getModifiedItemDate() , // "modified_item_date" : java.util.Date
			pmUpdatedItems.getCreatedDate() , // "created_date" : java.util.Date
			pmUpdatedItems.getUpdatedDate() , // "updated_date" : java.util.Date
			pmUpdatedItems.getCreatedBy() , // "created_by" : java.lang.String
			pmUpdatedItems.getUpdatedBy() , // "updated_by" : java.lang.String
			pmUpdatedItems.getStatus() , // "status" : java.lang.String
			pmUpdatedItems.getIsActive() , // "is_active" : java.lang.String
			pmUpdatedItems.getVersion()  // "version" : java.lang.Integer
		};
	}
    //----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForUpdate(PmUpdatedItems pmUpdatedItems) {
		return new Object[] {		
			//--- Returns DATA first ( for SQL "SET x=?, y=?, ..." )
			pmUpdatedItems.getItemId(), // "item_id" : java.lang.Integer
			pmUpdatedItems.getUserId(), // "user_id" : java.lang.Integer
			pmUpdatedItems.getModifiedItemDate(), // "modified_item_date" : java.util.Date
			pmUpdatedItems.getCreatedDate(), // "created_date" : java.util.Date
			pmUpdatedItems.getUpdatedDate(), // "updated_date" : java.util.Date
			pmUpdatedItems.getCreatedBy(), // "created_by" : java.lang.String
			pmUpdatedItems.getUpdatedBy(), // "updated_by" : java.lang.String
			pmUpdatedItems.getStatus(), // "status" : java.lang.String
			pmUpdatedItems.getIsActive(), // "is_active" : java.lang.String
			pmUpdatedItems.getVersion(), // "version" : java.lang.Integer
			//--- Returns PRIMARY KEY at the end ( for SQL "WHERE key=?, ..." )
			pmUpdatedItems.getId()  // "id" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForPrimaryKey(PmUpdatedItems pmUpdatedItems)  {
		return new Object[] {
			//--- Returns PRIMARY KEY values ( for SQL "WHERE key=?, ..." )
			pmUpdatedItems.getId()  // "id" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	@Override
	protected RowMapper<PmUpdatedItems> getRowMapper(PmUpdatedItems o)  {
		//--- RowMapper to populate the given bean instance
		return new PmUpdatedItemsRowMapper(o) ;
	}
	//----------------------------------------------------------------------
	@Override
	protected RowMapper<PmUpdatedItems> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		return new PmUpdatedItemsRowMapper( new PmUpdatedItems() ) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param pmUpdatedItems
	 * @throws SQLException
	 */
	private void populateBean(ResultSet rs, PmUpdatedItems pmUpdatedItems) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		pmUpdatedItems.setId(rs.getInt("id")); // java.lang.Integer
		if ( rs.wasNull() ) { pmUpdatedItems.setId(null); }; // not primitive number => keep null value if any
		pmUpdatedItems.setItemId(rs.getInt("item_id")); // java.lang.Integer
		if ( rs.wasNull() ) { pmUpdatedItems.setItemId(null); }; // not primitive number => keep null value if any
		pmUpdatedItems.setUserId(rs.getInt("user_id")); // java.lang.Integer
		if ( rs.wasNull() ) { pmUpdatedItems.setUserId(null); }; // not primitive number => keep null value if any
		pmUpdatedItems.setModifiedItemDate(rs.getDate("modified_item_date")); // java.util.Date
		pmUpdatedItems.setCreatedDate(rs.getDate("created_date")); // java.util.Date
		pmUpdatedItems.setUpdatedDate(rs.getDate("updated_date")); // java.util.Date
		pmUpdatedItems.setCreatedBy(rs.getString("created_by")); // java.lang.String
		pmUpdatedItems.setUpdatedBy(rs.getString("updated_by")); // java.lang.String
		pmUpdatedItems.setStatus(rs.getString("status")); // java.lang.String
		pmUpdatedItems.setIsActive(rs.getString("is_active")); // java.lang.String
		pmUpdatedItems.setVersion(rs.getInt("version")); // java.lang.Integer
		if ( rs.wasNull() ) { pmUpdatedItems.setVersion(null); }; // not primitive number => keep null value if any
	}

    //----------------------------------------------------------------------
	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	private class PmUpdatedItemsRowMapper implements RowMapper<PmUpdatedItems> {

		/**
		 * The bean instance that will be populated from the ResultSet
		 */
		private final PmUpdatedItems bean ;
		
		/**
		 * Constructor
		 * @param bean the bean to be populated 
		 */
		PmUpdatedItemsRowMapper(PmUpdatedItems bean) {
			this.bean = bean ;
		}
		
		public PmUpdatedItems mapRow(ResultSet rs, int rowNum) throws SQLException {
			populateBean(rs, this.bean);
			return this.bean;
		}
	}
}
