/*
 * Created on 15 Jan 2016 ( Time 19:53:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao.impl.spring;

import java.sql.ResultSet;
import java.sql.SQLException;

import com.mealtime.bean.UserRoleMaster;
import com.mealtime.dao.UserRoleMasterDAO;
import com.mealtime.dao.impl.spring.commons.GenericDAO;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

/**
 * UserRoleMaster DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
@Repository
public class UserRoleMasterDAOImplSpring extends GenericDAO<UserRoleMaster> implements UserRoleMasterDAO {

	private final static String SQL_SELECT = 
		"select role_id, role_name, created_date, updated_date, created_by, updated_by, status, is_active, version from user_role_master where role_id = ?";


	private final static String SQL_INSERT = 
		"insert into user_role_master ( role_id, role_name, created_date, updated_date, created_by, updated_by, status, is_active, version ) values ( ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update user_role_master set role_name = ?, created_date = ?, updated_date = ?, created_by = ?, updated_by = ?, status = ?, is_active = ?, version = ? where role_id = ?";

	private final static String SQL_DELETE = 
		"delete from user_role_master where role_id = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from user_role_master";

	private final static String SQL_COUNT = 
		"select count(*) from user_role_master where role_id = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public UserRoleMasterDAOImplSpring() {
		super();
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public UserRoleMaster find( Integer roleId ) {
		Object[] primaryKey = new Object[] { roleId };
		return super.doSelect(primaryKey);		
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public boolean load( UserRoleMaster userRoleMaster ) {
		return super.doSelect(userRoleMaster) ;
	}
	
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public void insert(UserRoleMaster userRoleMaster) {
		super.doInsert(userRoleMaster);
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public int update(UserRoleMaster userRoleMaster) {
		return super.doUpdate(userRoleMaster);
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public int delete( Integer roleId ) {
		Object[] primaryKey = new Object[] { roleId };
		return super.doDelete(primaryKey);		
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public int delete( UserRoleMaster userRoleMaster ) {
		return super.doDelete(userRoleMaster);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public boolean exists( Integer roleId ) {
		Object[] primaryKey = new Object[] { roleId };
		return super.doExists(primaryKey);
	}
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public boolean exists( UserRoleMaster userRoleMaster ) {
		return super.doExists(userRoleMaster);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	// Super class abstract methods implementation
    //----------------------------------------------------------------------
	
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}
	//----------------------------------------------------------------------
	
	protected Object[] getValuesForInsert(UserRoleMaster userRoleMaster)  {
		return new Object[] {
			//--- Returns PRIMARY KEY and DATA ( for SQL "SET x=?, y=?, ..." )
			userRoleMaster.getRoleId() , // "role_id" : java.lang.Integer
			userRoleMaster.getRoleName() , // "role_name" : java.lang.String
			userRoleMaster.getCreatedDate() , // "created_date" : java.util.Date
			userRoleMaster.getUpdatedDate() , // "updated_date" : java.util.Date
			userRoleMaster.getCreatedBy() , // "created_by" : java.lang.String
			userRoleMaster.getUpdatedBy() , // "updated_by" : java.lang.String
			userRoleMaster.getStatus() , // "status" : java.lang.String
			userRoleMaster.getIsActive() , // "is_active" : java.lang.String
			userRoleMaster.getVersion()  // "version" : java.lang.Integer
		};
	}
    //----------------------------------------------------------------------
	
	protected Object[] getValuesForUpdate(UserRoleMaster userRoleMaster) {
		return new Object[] {		
			//--- Returns DATA first ( for SQL "SET x=?, y=?, ..." )
			userRoleMaster.getRoleName(), // "role_name" : java.lang.String
			userRoleMaster.getCreatedDate(), // "created_date" : java.util.Date
			userRoleMaster.getUpdatedDate(), // "updated_date" : java.util.Date
			userRoleMaster.getCreatedBy(), // "created_by" : java.lang.String
			userRoleMaster.getUpdatedBy(), // "updated_by" : java.lang.String
			userRoleMaster.getStatus(), // "status" : java.lang.String
			userRoleMaster.getIsActive(), // "is_active" : java.lang.String
			userRoleMaster.getVersion(), // "version" : java.lang.Integer
			//--- Returns PRIMARY KEY at the end ( for SQL "WHERE key=?, ..." )
			userRoleMaster.getRoleId()  // "role_id" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	
	protected Object[] getValuesForPrimaryKey(UserRoleMaster userRoleMaster)  {
		return new Object[] {
			//--- Returns PRIMARY KEY values ( for SQL "WHERE key=?, ..." )
			userRoleMaster.getRoleId()  // "role_id" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	
	protected RowMapper<UserRoleMaster> getRowMapper(UserRoleMaster o)  {
		//--- RowMapper to populate the given bean instance
		return new UserRoleMasterRowMapper(o) ;
	}
	//----------------------------------------------------------------------
	
	protected RowMapper<UserRoleMaster> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		return new UserRoleMasterRowMapper( new UserRoleMaster() ) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param userRoleMaster
	 * @throws SQLException
	 */
	private void populateBean(ResultSet rs, UserRoleMaster userRoleMaster) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		userRoleMaster.setRoleId(rs.getInt("role_id")); // java.lang.Integer
		if ( rs.wasNull() ) { userRoleMaster.setRoleId(null); }; // not primitive number => keep null value if any
		userRoleMaster.setRoleName(rs.getString("role_name")); // java.lang.String
		userRoleMaster.setCreatedDate(rs.getDate("created_date")); // java.util.Date
		userRoleMaster.setUpdatedDate(rs.getDate("updated_date")); // java.util.Date
		userRoleMaster.setCreatedBy(rs.getString("created_by")); // java.lang.String
		userRoleMaster.setUpdatedBy(rs.getString("updated_by")); // java.lang.String
		userRoleMaster.setStatus(rs.getString("status")); // java.lang.String
		userRoleMaster.setIsActive(rs.getString("is_active")); // java.lang.String
		userRoleMaster.setVersion(rs.getInt("version")); // java.lang.Integer
		if ( rs.wasNull() ) { userRoleMaster.setVersion(null); }; // not primitive number => keep null value if any
	}

    //----------------------------------------------------------------------
	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	private class UserRoleMasterRowMapper implements RowMapper<UserRoleMaster> {

		/**
		 * The bean instance that will be populated from the ResultSet
		 */
		private final UserRoleMaster bean ;
		
		/**
		 * Constructor
		 * @param bean the bean to be populated 
		 */
		UserRoleMasterRowMapper(UserRoleMaster bean) {
			this.bean = bean ;
		}
		
		
		public UserRoleMaster mapRow(ResultSet rs, int rowNum) throws SQLException {
			populateBean(rs, this.bean);
			return this.bean;
		}
	}
}
