/*
 * Created on 10 Feb 2016 ( Time 11:17:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao.impl.spring;

import java.sql.ResultSet;
import java.sql.SQLException;

import com.mealtime.bean.UserMeals;
import com.mealtime.dao.UserMealsDAO;
import com.mealtime.dao.impl.spring.commons.GenericDAO;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

/**
 * UserMeals DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
@Repository
public class UserMealsDAOImplSpring extends GenericDAO<UserMeals> implements UserMealsDAO {

	private final static String SQL_SELECT = 
		"select user_id, meal_id, created_by, updated_by, status, is_active, version from user_meals where ";


	private final static String SQL_INSERT = 
		"insert into user_meals ( user_id, meal_id, created_by, updated_by, status, is_active, version ) values ( ?, ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update user_meals set user_id = ?, meal_id = ?, created_by = ?, updated_by = ?, status = ?, is_active = ?, version = ? where ";

	private final static String SQL_DELETE = 
		"delete from user_meals where ";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from user_meals";

	private final static String SQL_COUNT = 
		"select count(*) from user_meals where ";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public UserMealsDAOImplSpring() {
		super();
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public UserMeals find(  ) {
		Object[] primaryKey = new Object[] {  };
		return super.doSelect(primaryKey);		
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public boolean load( UserMeals userMeals ) {
		return super.doSelect(userMeals) ;
	}
	
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public void insert(UserMeals userMeals) {
		super.doInsert(userMeals);
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public int update(UserMeals userMeals) {
		return super.doUpdate(userMeals);
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public int delete(  ) {
		Object[] primaryKey = new Object[] {  };
		return super.doDelete(primaryKey);		
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public int delete( UserMeals userMeals ) {
		return super.doDelete(userMeals);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public boolean exists(  ) {
		Object[] primaryKey = new Object[] {  };
		return super.doExists(primaryKey);
	}
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public boolean exists( UserMeals userMeals ) {
		return super.doExists(userMeals);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	// Super class abstract methods implementation
    //----------------------------------------------------------------------
	
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}
	//----------------------------------------------------------------------
	
	protected Object[] getValuesForInsert(UserMeals userMeals)  {
		return new Object[] {
			//--- Returns PRIMARY KEY and DATA ( for SQL "SET x=?, y=?, ..." )
			userMeals.getUserId() , // "user_id" : java.lang.String
			userMeals.getMealId() , // "meal_id" : java.lang.Integer
			userMeals.getCreatedBy() , // "created_by" : java.lang.String
			userMeals.getUpdatedBy() , // "updated_by" : java.lang.String
			userMeals.getStatus() , // "status" : java.lang.String
			userMeals.getIsActive() , // "is_active" : java.lang.String
			userMeals.getVersion()  // "version" : java.lang.Integer
		};
	}
    //----------------------------------------------------------------------
	
	protected Object[] getValuesForUpdate(UserMeals userMeals) {
		return new Object[] {		
			//--- Returns DATA first ( for SQL "SET x=?, y=?, ..." )
			userMeals.getUserId(), // "user_id" : java.lang.String
			userMeals.getMealId(), // "meal_id" : java.lang.Integer
			userMeals.getCreatedBy(), // "created_by" : java.lang.String
			userMeals.getUpdatedBy(), // "updated_by" : java.lang.String
			userMeals.getStatus(), // "status" : java.lang.String
			userMeals.getIsActive(), // "is_active" : java.lang.String
			userMeals.getVersion(), // "version" : java.lang.Integer
			//--- Returns PRIMARY KEY at the end ( for SQL "WHERE key=?, ..." )
		};
	}
	//----------------------------------------------------------------------
	
	protected Object[] getValuesForPrimaryKey(UserMeals userMeals)  {
		return new Object[] {
			//--- Returns PRIMARY KEY values ( for SQL "WHERE key=?, ..." )
		};
	}
	//----------------------------------------------------------------------
	
	protected RowMapper<UserMeals> getRowMapper(UserMeals o)  {
		//--- RowMapper to populate the given bean instance
		return new UserMealsRowMapper(o) ;
	}
	//----------------------------------------------------------------------
	
	protected RowMapper<UserMeals> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		return new UserMealsRowMapper( new UserMeals() ) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param userMeals
	 * @throws SQLException
	 */
	private void populateBean(ResultSet rs, UserMeals userMeals) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		userMeals.setUserId(rs.getString("user_id")); // java.lang.String
		userMeals.setMealId(rs.getInt("meal_id")); // java.lang.Integer
		if ( rs.wasNull() ) { userMeals.setMealId(null); }; // not primitive number => keep null value if any
		userMeals.setCreatedBy(rs.getString("created_by")); // java.lang.String
		userMeals.setUpdatedBy(rs.getString("updated_by")); // java.lang.String
		userMeals.setStatus(rs.getString("status")); // java.lang.String
		userMeals.setIsActive(rs.getString("is_active")); // java.lang.String
		userMeals.setVersion(rs.getInt("version")); // java.lang.Integer
		if ( rs.wasNull() ) { userMeals.setVersion(null); }; // not primitive number => keep null value if any
	}

    //----------------------------------------------------------------------
	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	private class UserMealsRowMapper implements RowMapper<UserMeals> {

		/**
		 * The bean instance that will be populated from the ResultSet
		 */
		private final UserMeals bean ;
		
		/**
		 * Constructor
		 * @param bean the bean to be populated 
		 */
		UserMealsRowMapper(UserMeals bean) {
			this.bean = bean ;
		}
		
		
		public UserMeals mapRow(ResultSet rs, int rowNum) throws SQLException {
			populateBean(rs, this.bean);
			return this.bean;
		}
	}
}
