/*
 * Created on 5 Mar 2016 ( Time 18:48:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao;

import com.mealtime.bean.AmItems;

/**
 * AmItems DAO interface
 * 
 * @author Telosys Tools
 */
public interface AmItemsDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param itemId
	 * @return the bean found or null if not found 
	 */
	public AmItems find( Integer itemId ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param amItems
	 * @return true if found, false if not found
	 */
	public boolean load( AmItems amItems ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param amItems
	 * @return the generated value for the auto-incremented column
	 */
	public Integer insert(AmItems amItems) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param amItems
	 * @return
	 */
	public int update(AmItems amItems) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param itemId
	 * @return
	 */
	public int delete( Integer itemId ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param amItems
	 * @return
	 */
	public int delete( AmItems amItems ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param itemId
	 * @return
	 */
	public boolean exists( Integer itemId ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param amItems
	 * @return
	 */
	public boolean exists( AmItems amItems ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;
	
	public AmItems getAMItemObj();

}
