/*
 * Created on 8 Feb 2016 ( Time 19:50:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao;

import java.util.List;

import com.mealtime.bean.AmSubItems;

/**
 * AmSubItems DAO interface
 * 
 * @author Telosys Tools
 */
public interface AmSubItemsDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param itemId
	 * @return the bean found or null if not found 
	 */
	public AmSubItems find( Integer itemId ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param amSubItems
	 * @return true if found, false if not found
	 */
	public boolean load( AmSubItems amSubItems ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param amSubItems
	 */
	public void insert(AmSubItems amSubItems) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param amSubItems
	 * @return
	 */
	public int update(AmSubItems amSubItems) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param itemId
	 * @return
	 */
	public int delete( Integer itemId ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param amSubItems
	 * @return
	 */
	public int delete( AmSubItems amSubItems ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param itemId
	 * @return
	 */
	public boolean exists( Integer itemId ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param amSubItems
	 * @return
	 */
	public boolean exists( AmSubItems amSubItems ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;
	
	public List<AmSubItems> getItemsList();

}
