/*
 * Created on 11 Mar 2016 ( Time 22:46:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao;

import com.mealtime.bean.AmUpdatedSubItems;

/**
 * AmUpdatedSubItems DAO interface
 * 
 * @author Telosys Tools
 */
public interface AmUpdatedSubItemsDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param id
	 * @return the bean found or null if not found 
	 */
	public AmUpdatedSubItems find( Integer id ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param amUpdatedSubItems
	 * @return true if found, false if not found
	 */
	public boolean load( AmUpdatedSubItems amUpdatedSubItems ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param amUpdatedSubItems
	 * @return the generated value for the auto-incremented column
	 */
	public Integer insert(AmUpdatedSubItems amUpdatedSubItems) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param amUpdatedSubItems
	 * @return
	 */
	public int update(AmUpdatedSubItems amUpdatedSubItems) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param id
	 * @return
	 */
	public int delete( Integer id ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param amUpdatedSubItems
	 * @return
	 */
	public int delete( AmUpdatedSubItems amUpdatedSubItems ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param id
	 * @return
	 */
	public boolean exists( Integer id ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param amUpdatedSubItems
	 * @return
	 */
	public boolean exists( AmUpdatedSubItems amUpdatedSubItems ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
