/*
 * Created on 3 May 2016 ( Time 23:25:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao;

import com.mealtime.bean.Feedback;

/**
 * Feedback DAO interface
 * 
 * @author Telosys Tools
 */
public interface FeedbackDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	public Feedback find(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param feedback
	 * @return true if found, false if not found
	 */
	public boolean load( Feedback feedback ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param feedback
	 */
	public void insert(Feedback feedback) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param feedback
	 * @return
	 */
	public int update(Feedback feedback) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	public int delete(  ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param feedback
	 * @return
	 */
	public int delete( Feedback feedback ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	public boolean exists(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param feedback
	 * @return
	 */
	public boolean exists( Feedback feedback ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
