/*
 * Created on 5 Mar 2016 ( Time 18:48:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao;

import java.util.List;

import com.mealtime.bean.PmUpdatedItems;

/**
 * PmUpdatedItems DAO interface
 * 
 * @author Telosys Tools
 */
public interface PmUpdatedItemsDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param id
	 * @return the bean found or null if not found 
	 */
	public PmUpdatedItems find( Integer id ) ;
	
	public PmUpdatedItems findByUserId(String userId);

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param pmUpdatedItems
	 * @return true if found, false if not found
	 */
	public boolean load( PmUpdatedItems pmUpdatedItems ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param pmUpdatedItems
	 * @return the generated value for the auto-incremented column
	 */
	public Integer insert(PmUpdatedItems pmUpdatedItems) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param pmUpdatedItems
	 * @return
	 */
	public int update(PmUpdatedItems pmUpdatedItems) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param id
	 * @return
	 */
	public int delete( Integer id ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param pmUpdatedItems
	 * @return
	 */
	public int delete( PmUpdatedItems pmUpdatedItems ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param id
	 * @return
	 */
	public boolean exists( Integer id ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param pmUpdatedItems
	 * @return
	 */
	public boolean exists( PmUpdatedItems pmUpdatedItems ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;
	
	public int deleteUserRecord(int itemId,String userId);

}
