/*
 * Created on 11 Mar 2016 ( Time 22:46:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao;

import java.util.List;

import com.mealtime.bean.PmUpdatedSubItems;

/**
 * PmUpdatedSubItems DAO interface
 * 
 * @author Telosys Tools
 */
public interface PmUpdatedSubItemsDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param id
	 * @return the bean found or null if not found 
	 */
	public PmUpdatedSubItems find( Integer id ) ;
	
	public PmUpdatedSubItems findByUserId(String userId, Integer ItemId);
	
	public List<PmUpdatedSubItems> findById(String userId);

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param pmUpdatedSubItems
	 * @return true if found, false if not found
	 */
	public boolean load( PmUpdatedSubItems pmUpdatedSubItems ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param pmUpdatedSubItems
	 * @return the generated value for the auto-incremented column
	 */
	public Integer insert(PmUpdatedSubItems pmUpdatedSubItems) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param pmUpdatedSubItems
	 * @return
	 */
	public int update(PmUpdatedSubItems pmUpdatedSubItems) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param id
	 * @return
	 */
	public int delete( Integer id ) ;
	
	public int deleteUserRecord(int itemId,String userId);

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param pmUpdatedSubItems
	 * @return
	 */
	public int delete( PmUpdatedSubItems pmUpdatedSubItems ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param id
	 * @return
	 */
	public boolean exists( Integer id ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param pmUpdatedSubItems
	 * @return
	 */
	public boolean exists( PmUpdatedSubItems pmUpdatedSubItems ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

	public int deleteCurDateUserRecord(String userId,String date);
}
