/*
 * Created on 24 Mar 2016 ( Time 07:53:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao;

import com.mealtime.bean.ScheduleEnquiry;

/**
 * ScheduleEnquiry DAO interface
 * 
 * @author Telosys Tools
 */
public interface ScheduleEnquiryDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param enquiryId
	 * @return the bean found or null if not found 
	 */
	public ScheduleEnquiry find( Integer enquiryId ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param scheduleEnquiry
	 * @return true if found, false if not found
	 */
	public boolean load( ScheduleEnquiry scheduleEnquiry ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param scheduleEnquiry
	 * @return the generated value for the auto-incremented column
	 */
	public Integer insert(ScheduleEnquiry scheduleEnquiry) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param scheduleEnquiry
	 * @return
	 */
	public int update(ScheduleEnquiry scheduleEnquiry) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param enquiryId
	 * @return
	 */
	public int delete( Integer enquiryId ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param scheduleEnquiry
	 * @return
	 */
	public int delete( ScheduleEnquiry scheduleEnquiry ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param enquiryId
	 * @return
	 */
	public boolean exists( Integer enquiryId ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param scheduleEnquiry
	 * @return
	 */
	public boolean exists( ScheduleEnquiry scheduleEnquiry ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;
	
	public ScheduleEnquiry findByUserId( String userId ) ;
	
	public void scheduleEnquiryPDF();

}
