/*
 * Created on 15 Jan 2016 ( Time 19:53:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao;

import com.mealtime.bean.SubscriptionMaster;

/**
 * SubscriptionMaster DAO interface
 * 
 * @author Telosys Tools
 */
public interface SubscriptionMasterDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param subscriptionId
	 * @return the bean found or null if not found 
	 */
	public SubscriptionMaster find( Integer subscriptionId ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param subscriptionMaster
	 * @return true if found, false if not found
	 */
	public boolean load( SubscriptionMaster subscriptionMaster ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param subscriptionMaster
	 */
	public void insert(SubscriptionMaster subscriptionMaster) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param subscriptionMaster
	 * @return
	 */
	public int update(SubscriptionMaster subscriptionMaster) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param subscriptionId
	 * @return
	 */
	public int delete( Integer subscriptionId ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param subscriptionMaster
	 * @return
	 */
	public int delete( SubscriptionMaster subscriptionMaster ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param subscriptionId
	 * @return
	 */
	public boolean exists( Integer subscriptionId ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param subscriptionMaster
	 * @return
	 */
	public boolean exists( SubscriptionMaster subscriptionMaster ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
