/*
 * Created on 10 Feb 2016 ( Time 11:17:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao;

import com.mealtime.bean.UserTransaction;

/**
 * UserTransaction DAO interface
 * 
 * @author Telosys Tools
 */
public interface UserTransactionDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param transactionId
	 * @return the bean found or null if not found 
	 */
	public UserTransaction find( Integer transactionId ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param userTransaction
	 * @return true if found, false if not found
	 */
	public boolean load( UserTransaction userTransaction ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param userTransaction
	 */
	public void insert(UserTransaction userTransaction) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param userTransaction
	 * @return
	 */
	public int update(UserTransaction userTransaction) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param transactionId
	 * @return
	 */
	public int delete( Integer transactionId ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param userTransaction
	 * @return
	 */
	public int delete( UserTransaction userTransaction ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param transactionId
	 * @return
	 */
	public boolean exists( Integer transactionId ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param userTransaction
	 * @return
	 */
	public boolean exists( UserTransaction userTransaction ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
