/*
 * Created on 31 Jan 2016 ( Time 14:32:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao;

import com.mealtime.bean.UserMaster;

/**
 * UserMaster DAO interface
 * 
 * @author Telosys Tools
 */
public interface UserMasterDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param userId
	 * @return the bean found or null if not found 
	 */
	public UserMaster find( Integer userId ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param userMaster
	 * @return true if found, false if not found
	 */
	public boolean load( UserMaster userMaster ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param userMaster
	 * @return the generated value for the auto-incremented column
	 */
	public Integer insert(UserMaster userMaster) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param userMaster
	 * @return
	 */
	public int update(UserMaster userMaster) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param userId
	 * @return
	 */
	public int delete( Integer userId ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param userMaster
	 * @return
	 */
	public int delete( UserMaster userMaster ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param userId
	 * @return
	 */
	public boolean exists( Integer userId ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param userMaster
	 * @return
	 */
	public boolean exists( UserMaster userMaster ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;
	
	public UserMaster findByMobileNumber( String mobileNumber ) ;

}
