/*
 * Created on 10 Feb 2016 ( Time 11:17:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao;

import com.mealtime.bean.UserWallet;

/**
 * UserWallet DAO interface
 * 
 * @author Telosys Tools
 */
public interface UserWalletDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	public UserWallet find(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param userWallet
	 * @return true if found, false if not found
	 */
	public boolean load( UserWallet userWallet ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param userWallet
	 */
	public void insert(UserWallet userWallet) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param userWallet
	 * @return
	 */
	public int update(UserWallet userWallet) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	public int delete(  ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param userWallet
	 * @return
	 */
	public int delete( UserWallet userWallet ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	public boolean exists(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param userWallet
	 * @return
	 */
	public boolean exists( UserWallet userWallet ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;
	
	public UserWallet findByUserId(String userId); 

}
