/*
 * Created on 10 Feb 2016 ( Time 11:17:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mealtime.dao;

import com.mealtime.bean.UserSubscription;

/**
 * UserSubscription DAO interface
 * 
 * @author Telosys Tools
 */
public interface UserSubscriptionDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	public UserSubscription find(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param userSubscription
	 * @return true if found, false if not found
	 */
	public boolean load( UserSubscription userSubscription ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param userSubscription
	 */
	public void insert(UserSubscription userSubscription) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param userSubscription
	 * @return
	 */
	public int update(UserSubscription userSubscription) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	public int delete(  ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param userSubscription
	 * @return
	 */
	public int delete( UserSubscription userSubscription ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	public boolean exists(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param userSubscription
	 * @return
	 */
	public boolean exists( UserSubscription userSubscription ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
